### ISSUE TITLE
Required build flags store into a ini

### ISSUE THREAD

**Issue by juergenschubert** [joaoubaldo/esp8266_dht_influxdb#1]
Hi there,
just wonder if you could store your Required build flags also in a ini files so no need to specify them for every run? I run PlatoformIO with ATOM and would love to use this method but not willing to go down to command line. Today I use i #Include "myconf.h" for this kind of information

**Comment by joaoubaldo** [comment]
I have added the build_flags parameter to the ini file. Environment variables still have precedence over the flags defined in the ini file.
