### ISSUE TITLE
Have you  tested with Influxdb-Version: 1.5.0

### ISSUE THREAD

**Issue by juergenschubert** [joaoubaldo/esp8266_dht_influxdb#2]
just wonder when I look to you api request string if this is the right one.
When I do a InfluxDB api call and add values I need a 
curl -i -XPOST 'http://192.168.1.50:8086/write?db=IOT&u=root&p=123456' --data-binary 'dht22,location=Speicher,client=ESP01 temperatur=22.30,humidity=50.50,heat_index=21.90'
I can not see some of the values in your field. So do wonder if this has the Potential to work as in my expample I run Tags, before fields and my tags are Location and client and my filed are the rest

**Comment by joaoubaldo** [comment]
I haven't yet tested influxdb 1.5 but according to https://docs.influxdata.com/influxdb/v1.5/write_protocols/line_protocol_reference/ the line protocol didn't change - `<measurement>[,<tag_key>=<tag_value>[,<tag_key>=<tag_value>]] <field_key>=<field_value>[,<field_key>=<field_value>] [<timestamp>]`. 
The only thing missing is support for multiple `field_key`. At the moment only a single value - `value` - is sent. I'll probably review that. Thanks
